tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 6f9a4073-8da2-4ca3-bbab-b6fc385a8965
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: cadaa982-36f7-4e98-ab58-7abede59c48f
        userCondition: null
        warning: null
        width: 100
    name: Default
    uid: db441bc8-32b3-48af-909d-b3f86132a70a
    userCondition: null
