field: ea573766-63d9-4649-927e-646ed2609c9a
fieldLayouts:
  b6c02472-2f56-4795-96bd-b0674b2c9cbe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dd34ba2f-e52f-4af3-a24f-07b7843021b5 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68fd9d3b-9996-440b-8366-b903557a6350
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e87e440-9e69-40cf-a621-a73cfdbf3cf2 # Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52e3fb14-f523-4d0f-93bb-47dae8717e14
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ce140d4e-38c1-46b9-a06b-b8c613842ec7
        userCondition: null
fields:
  6e87e440-9e69-40cf-a621-a73cfdbf3cf2: # Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: Items
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      source: 'group:79c88842-8dad-4449-8021-66618ba49dd4'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  dd34ba2f-e52f-4af3-a24f-07b7843021b5: # Headline
    columnSuffix: qqgkefgc
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: bullets
name: Bullets
sortOrder: 13
