field: ea573766-63d9-4649-927e-646ed2609c9a
fieldLayouts:
  0cc269b1-87ba-422c-9c86-08f7ff63d3e9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e31bcbff-2d8f-4e8b-9559-1f3137c16310 # Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6c869cc-3aac-45a8-92fe-88ea5eaef40b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1efa9d6d-43a5-419c-81d3-0a7e5ef7d875
        userCondition: null
fields:
  e31bcbff-2d8f-4e8b-9559-1f3137c16310: # Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: Items
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1708710983
      columns:
        __assoc__:
          -
            - c3fe577b-c14c-4b22-9306-7251cc97de1f # Tag
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 896fd6fd-26d2-4480-b641-acfa5a037eb1 # Headline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 32bce18a-1429-4689-9c7f-c751aa890060 # Media
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 78a6528a-68b2-4a8a-b99e-d3992ed9b750 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_5_items}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: entryCarousel
name: 'Entry Carousel'
sortOrder: 11
