field: ea573766-63d9-4649-927e-646ed2609c9a
fieldLayouts:
  ee565757-7b0f-4402-acdd-ded36ece424d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5e312397-a325-4667-b1f0-9aecd9495873 # Responsive media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcd6409b-7d56-48c2-b043-3a4be3361292
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45747ae3-7ff5-4f53-a00a-776b00d906da # Show image caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6d7417a-a69f-486b-9af0-5f9fd63d8701
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 38abb329-7aee-4b57-8758-86ed2580f308
        userCondition: null
fields:
  5e312397-a325-4667-b1f0-9aecd9495873: # Responsive media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: responsiveMedia
    instructions: 'If two assets are added, the first will be used on mobile'
    name: 'Responsive media'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 2
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  45747ae3-7ff5-4f53-a00a-776b00d906da: # Show image caption
    columnSuffix: anrktyma
    contentColumnType: boolean
    fieldGroup: null
    handle: showImageCaption
    instructions: null
    name: 'Show image caption'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: fullscreenMedia
name: 'Fullscreen media'
sortOrder: 5
