field: ea573766-63d9-4649-927e-646ed2609c9a
fieldLayouts:
  eccd955d-df2d-46e1-8ad4-7ebd6566d63d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: be6f80ce-90c7-47f2-9c12-08a22648cae9 # Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 407093e8-adf5-44e5-8f7f-758dcd768145
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e89ec6e5-3171-41c7-aa77-02b1c3e3ae8e # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bcc0f10-359c-4369-9585-1602d0ebd378
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 127fb155-166e-4996-bbfe-a130373c57ff # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fd49647-1b3c-46bb-bb82-460cd08263c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92f30535-adcc-4f9f-b5b1-60042746f6c5 # Textfield
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d768641-f5fc-4438-8c28-8ed567b88eba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 312afeaf-68e2-447a-ab56-dcd6813666a4
        userCondition: null
fields:
  92f30535-adcc-4f9f-b5b1-60042746f6c5: # Textfield
    columnSuffix: dnqbqfec
    contentColumnType: text
    fieldGroup: null
    handle: textfield
    instructions: null
    name: Textfield
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Ctas-in-text.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  127fb155-166e-4996-bbfe-a130373c57ff: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkField
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: site
    type: lenz\linkfield\fields\LinkField
  be6f80ce-90c7-47f2-9c12-08a22648cae9: # Tag
    columnSuffix: zlujljeo
    contentColumnType: text
    fieldGroup: null
    handle: tag
    instructions: null
    name: Tag
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  e89ec6e5-3171-41c7-aa77-02b1c3e3ae8e: # Headline
    columnSuffix: zpslbvxk
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: headlineModule
name: Headline
sortOrder: 3
