field: ea573766-63d9-4649-927e-646ed2609c9a
fieldLayouts:
  8153be59-cb45-42e9-b73a-da7cdd3aa56d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f72ff1e6-b747-4bd1-9d0f-f5bd1afd1987 # Responsive media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c3918e0-48ae-4fb7-9c7e-b1d395b987ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5505176-4e5c-437b-a949-83381822d12e # Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14928f44-82e3-45f9-b774-1d482dd41568
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b27511eb-67e1-4b84-a3bb-9966c1284964 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b0b6911-a11a-4f15-948c-71b37eac03d7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2413398d-e673-4cc4-b977-982ab8860b2d # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ae9207a-bbdc-4e79-9995-e82c460fb67f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6ef9cec9-a33d-44ba-bfc0-4aafd2505bdc # Text color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48411482-d503-4b19-94cd-e3277842425d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 32d8d8a3-0d3d-4d41-8ad9-f8812acda8d7 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc201ef4-244f-45f7-a378-052c43662a4b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: add8265c-3aeb-4a66-ac9c-a82af78abf31 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 714becd2-6ebb-4859-974b-08194819e965
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2754926-d09b-4f83-aefe-501d934e71d4 # Closable
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23528d5f-6827-4fb1-bf00-a376bad7c3af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8227c69-063e-45e4-821b-858e1de4dfe9 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5220af7-ddb4-4669-b224-f14deccb85b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3f25b5c-f50f-4aee-9029-b1d9ef32e647 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9098c238-85a6-4c47-afd1-079232b3409a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d8f376d6-7b42-4783-b9a9-e519f4c23c26
        userCondition: null
fields:
  6ef9cec9-a33d-44ba-bfc0-4aafd2505bdc: # Text color
    columnSuffix: onkieoib
    contentColumnType: boolean
    fieldGroup: null
    handle: textColor
    instructions: 'Change this according to the color of the image'
    name: 'Text color'
    searchable: false
    settings:
      default: false
      offLabel: Light
      onLabel: Dark
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  32d8d8a3-0d3d-4d41-8ad9-f8812acda8d7: # Content
    columnSuffix: bkxsecrc
    contentColumnType: text
    fieldGroup: null
    handle: announcementContent
    instructions: null
    name: Content
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Announcement.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  2413398d-e673-4cc4-b977-982ab8860b2d: # Headline
    columnSuffix: xyyxeyac
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a8227c69-063e-45e4-821b-858e1de4dfe9: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: badgeImage
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a2754926-d09b-4f83-aefe-501d934e71d4: # Closable
    columnSuffix: voqhfrfl
    contentColumnType: boolean
    fieldGroup: null
    handle: announcementClosable
    instructions: null
    name: Closable
    searchable: false
    settings:
      default: true
      offLabel: 'Not closable'
      onLabel: Closable
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  add8265c-3aeb-4a66-ac9c-a82af78abf31: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: announcementLink
    instructions: null
    name: Link
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Ctas.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  b27511eb-67e1-4b84-a3bb-9966c1284964: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: 'An icon overwrites "Tag" and "Headline"'
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b5505176-4e5c-437b-a949-83381822d12e: # Tag
    columnSuffix: lixxatqj
    contentColumnType: text
    fieldGroup: null
    handle: tag
    instructions: null
    name: Tag
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c3f25b5c-f50f-4aee-9029-b1d9ef32e647: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: badgeLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  f72ff1e6-b747-4bd1-9d0f-f5bd1afd1987: # Responsive media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: responsiveMedia
    instructions: 'If 2 assets are added, the first one will be shown on mobile'
    name: 'Responsive media'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - video
      branchLimit: null
      defaultUploadLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 2
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: homepageHero
name: 'Homepage Hero'
sortOrder: 1
