field: ad52ea7e-f516-4e0f-b085-4d63b3364d28 # Typed field link list
fieldLayouts:
  2b37f86e-1209-4994-afe5-ae7ed83bce36:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 82714ccd-e99e-462e-9c37-f21717485039 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e87c389d-24af-48d0-ac82-7181ed1a026a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8298e6f2-b996-4b4b-8810-b2a20c1352f8 # Trumpet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2397a2bc-e791-4e34-b996-0fd4fc8a2a14
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 07ff88c1-8edb-462f-894d-9ca68aca1309
        userCondition: null
fields:
  8298e6f2-b996-4b4b-8810-b2a20c1352f8: # Trumpet
    columnSuffix: bbylizja
    contentColumnType: text
    fieldGroup: null
    handle: trumpet
    instructions: null
    name: Trumpet
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  82714ccd-e99e-462e-9c37-f21717485039: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkField
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: true
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: item
name: item
sortOrder: 1
