field: a23b649c-0d4f-4108-9164-65c931a37763 # Widget
fieldLayouts:
  2c87790b-f5df-474e-9965-8ae178193d04:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7e7b892e-151d-4a9d-87ac-72015d9a5c16 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cd8cdb5-e811-4174-9626-2b1e69129356
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 835ca88c-d582-4839-aefc-782c7ea87a4d # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7ad655a-335d-414a-a99f-1b11638f7a04
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80622e1b-9a81-48cb-b9c7-7b1ce2185b1c # Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 296991de-0bcb-4924-b1a8-be498b0e2413
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d06c079b-b50c-420f-8027-678816eee3a1 # Is present on mobile?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c3ca085-917b-4b7f-8e78-00fbecb5a9a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fa933f3e-4cb1-4adb-8489-7d8ed0e77af5
        userCondition: null
fields:
  7e7b892e-151d-4a9d-87ac-72015d9a5c16: # Headline
    columnSuffix: auecmzxl
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  835ca88c-d582-4839-aefc-782c7ea87a4d: # Rich Text
    columnSuffix: wagbemdg
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: null
    name: 'Rich Text'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  80622e1b-9a81-48cb-b9c7-7b1ce2185b1c: # Media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: media
    instructions: null
    name: Media
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:8a3b25bc-ffee-4b7b-9cfd-a1496def68a2' # Default
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:8a3b25bc-ffee-4b7b-9cfd-a1496def68a2' # Default
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d06c079b-b50c-420f-8027-678816eee3a1: # Is present on mobile?
    columnSuffix: vgafxalk
    contentColumnType: boolean
    fieldGroup: null
    handle: isPresentOnMobile
    instructions: null
    name: 'Is present on mobile?'
    searchable: false
    settings:
      default: true
      offLabel: 'Not on mobile'
      onLabel: 'On mobile'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: text
name: Text
sortOrder: 3
