field: 7f80d9a6-6940-4531-8c59-9ed427fef9e1 # Theme
fieldLayouts:
  8a3ec8e7-af90-4b88-a861-bc2628c627f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e91e2c4a-47df-4cc8-9cc3-6160b5ba729d # Text color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 172223f1-e5d9-4dd1-9f10-88004a23313d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b14d649b-7f27-4082-9ab6-f6563f23cd09 # Background color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46fd6839-98f6-4a6b-b5d4-3f6288349869
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1231905c-7cf7-47ad-9f85-fdc612839265
        userCondition: null
fields:
  b14d649b-7f27-4082-9ab6-f6563f23cd09: # Background color
    columnSuffix: hskxkbjh
    contentColumnType: text
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Background color'
    searchable: false
    settings:
      allowCustomColor: true
      allowCustomColorPicker: true
      allowOpacity: true
      colorFormat: auto
      defaultColorHandle: white
      defaultOpacity: 100
      fieldDescriptions: false
      paletteBaseColors:
        - white
      paletteColors: ''
      presetId: ''
      presetMode: false
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\colorit\fields\ColoritField
  e91e2c4a-47df-4cc8-9cc3-6160b5ba729d: # Text color
    columnSuffix: vqlwhwsl
    contentColumnType: text
    fieldGroup: null
    handle: textColor
    instructions: null
    name: 'Text color'
    searchable: false
    settings:
      allowCustomColor: true
      allowCustomColorPicker: true
      allowOpacity: true
      colorFormat: auto
      defaultColorHandle: black
      defaultOpacity: 100
      fieldDescriptions: false
      paletteBaseColors:
        - black
      paletteColors: ''
      presetId: ''
      presetMode: false
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\colorit\fields\ColoritField
handle: theme
name: Theme
sortOrder: 1
