field: a23b649c-0d4f-4108-9164-65c931a37763 # Widget
fieldLayouts:
  a781a224-6e41-442c-9e85-d8d744d5dd30:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 45bf0a44-5933-4fe3-bf12-2dc0d8677a34 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 488ec3e4-e4eb-4fb1-9ecc-f5b751e1c55b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4c3d853-7fcd-42c0-a848-ac8f5b01b3d9 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 052d866d-3cee-46a4-a740-ef96b241d621
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ecea26a1-ed7b-406d-aa6f-3a41cde66886 # Is present on mobile?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2034610d-9524-4ea3-94da-ff02d03493d0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f28ef311-3538-4aab-b81b-85f3f8c17cc2
        userCondition: null
fields:
  45bf0a44-5933-4fe3-bf12-2dc0d8677a34: # Headline
    columnSuffix: rubrgops
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c4c3d853-7fcd-42c0-a848-ac8f5b01b3d9: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: null
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - json
        - video
      branchLimit: null
      defaultUploadLocationSource: 'volume:8a3b25bc-ffee-4b7b-9cfd-a1496def68a2' # Default
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:8a3b25bc-ffee-4b7b-9cfd-a1496def68a2' # Default
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ecea26a1-ed7b-406d-aa6f-3a41cde66886: # Is present on mobile?
    columnSuffix: wmvimeev
    contentColumnType: boolean
    fieldGroup: null
    handle: isPresentOnMobile
    instructions: null
    name: 'Is present on mobile?'
    searchable: false
    settings:
      default: true
      offLabel: 'Not on mobile'
      onLabel: 'On mobile'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: video
name: Video
sortOrder: 2
