field: 37494ced-87df-4a71-95e7-5ff598ecef54 # Product weight
fieldLayouts:
  e5c98ca8-5e31-47b1-b2ed-1ac85bfbf722:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 88d00e5c-8e15-4900-a448-1cb42a066c19 # Weight
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0473490-ed10-4c88-a8ab-7e6bc6342a7e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a4cd07fd-a017-4786-a780-f3d04829c0bb # Unit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e328857d-8dd6-4f79-af73-bf9aadef0a75
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 57091d5e-3662-4bfa-9081-0aacde124573
        userCondition: null
fields:
  88d00e5c-8e15-4900-a448-1cb42a066c19: # Weight
    columnSuffix: kkjcvijf
    contentColumnType: 'decimal(12,2)'
    fieldGroup: null
    handle: weight
    instructions: null
    name: Weight
    searchable: false
    settings:
      decimals: 2
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  a4cd07fd-a017-4786-a780-f3d04829c0bb: # Unit
    columnSuffix: svjrzrzu
    contentColumnType: string
    fieldGroup: null
    handle: unit
    instructions: null
    name: Unit
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Kg
            -
              - value
              - kg
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - g
            -
              - value
              - g
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MultiSelect
handle: weight
name: 'Product weight'
sortOrder: 1
