fieldLayouts:
  9d3e912e-cff8-468d-a709-065e2ef4e17d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: aca0db1f-28b5-4966-a7ed-64beca5a56e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59d38b2c-dd7c-447c-a70f-5faa523318d0 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e6bdf89-02fd-4ea0-aa1c-ac56a1663cea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d4dcf53e-d151-48e2-9ee6-11e1760791ca
        userCondition: null
handle: entryType
name: 'Entry type'
