fieldLayouts:
  43a58f15-18a7-4a6e-8e77-58df857b12f3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 645f9958-2871-45bc-b396-60792f95a1a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d22684af-98f1-4efe-8201-c30d64fe7008 # Shopify Id
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a88276e0-17ab-47dc-9c98-226ac5dda406
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee99146c-165d-41c6-a71c-9ee7339a9f5c # Product description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28d1a821-c803-4e58-b321-c8a964237790
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d11934d3-4fcb-4b34-ba2c-ef76aff56d3f # JSON Data
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10d9e0e1-2de8-4a40-9bc2-16d6f733e9a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c916b23-359a-4fa2-aa57-cb208a8a1bff
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 68dd7f73-3c5f-4a60-acf5-4259d9c4f8d4 # Products
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
