fieldLayouts:
  40d8002a-8327-4adb-9573-6bc64f3fb92c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d150d0bf-1f60-426c-add9-8e43caa11318
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 676c5398-f1fb-4940-8728-50a47b1279d4 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 245c581e-634e-414c-9830-34deb87963ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b787fc51-d41c-41eb-934b-0e22a0fbd991
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: df975600-2e5f-4f95-9797-1022b161c1b1 # Footer menu
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{linkField.getText}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
