fieldLayouts:
  b022782f-e925-4e03-8888-f9f4c544cd81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0f592d0-2526-424f-a5ac-c6a47016a33b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 676c5398-f1fb-4940-8728-50a47b1279d4 # Link
            instructions: 'For making the item a toggle button: choose "Custom" and set the url to a hashtag (#)'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8463b98d-e0e0-46e3-8aae-b082dafae634
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a94b73a7-3163-422d-ad01-84f79ad1f533 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 116b59bb-cd4b-4c6b-9097-1004037f8d30
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 27fc7642-7d55-4811-84cd-55b4f0b0be99
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 787ae384-86e2-42f5-8992-2f3248499275 # Main menu
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{linkField.customText}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
