fieldLayouts:
  7c17a255-521d-4cee-badd-2b6d06d3645d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d30eaf6-fd67-41da-8248-02ff8d69e8b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd84b447-4aae-4f9c-a500-f1a287c324bb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55e8c1f5-106f-4d63-b2b0-2d1d601d1441
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90bc2f5e-d774-45fe-951a-2e683bf725b8
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: c70bf687-8f35-4f9b-bd81-e376c13e6ae9 # Menu
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
