fieldLayouts:
  95d7b1e9-7c3a-42d3-ad90-1503969931c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: db2ea0c6-bf95-49dd-bace-123b31a28aba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea573766-63d9-4649-927e-646ed2609c9a # Page Modules
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12e437cc-219d-499e-98bd-e52dd41144c3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eec45584-720f-4e36-96ea-7c1acd93434d
        userCondition: null
handle: errorPage
hasTitleField: false
name: 'Error page'
section: bb258364-7152-4469-a31e-83e9374d1331 # Error page
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
