fieldLayouts:
  35540c3e-d034-486d-8637-0aacb7a44d51:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 643c2fa8-65d8-4e80-9d55-6b385c6b0f8d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea573766-63d9-4649-927e-646ed2609c9a # Page Modules
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1039df7e-018b-4931-8d69-59bc576fc817
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ea9f070-c399-4eb2-afed-9aae8f590da7
        userCondition: null
handle: index
hasTitleField: true
name: Index
section: 95072f3f-0f86-49de-9f0d-4226751cb0cf # Index
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
