fieldLayouts:
  4c84875d-f32e-47a2-9f16-c3a01004114e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7490a95d-2c43-4ec7-8635-05f0b68c7ebb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 91a991d3-fdec-4366-ab5a-78cacba3eba7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06d884d4-25c1-4f18-ada8-fa6dfa32b4de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 833efbdd-423b-4582-82eb-96a2c26f69f5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c93006e-866d-4471-b8e1-2bb89060ec3c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab8d2630-f7d5-455f-9949-4b102a762555
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a76d4822-fec0-4c4d-a991-4dd8ab03e47e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6f9a4073-8da2-4ca3-bbab-b6fc385a8965
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a339d8f8-3538-40fb-a4ce-b3cb6fec8338
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b9a16bfa-0abf-438b-9915-9a603d08171d
        userCondition: null
handle: index
hasTitleField: false
name: Index
section: bdbbfb5e-5a2d-4357-a40a-43c7703a73b3 # Index
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
