defaultPlacement: end
fieldLayouts:
  9e7f1638-e7f4-4e4c-b4d5-575e1aae3a7c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 14c32f68-6789-42fa-bd91-55017b052e3b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c6f7db1-3d4d-493b-9d8e-17a89c09a41c
        userCondition: null
handle: collectionsType
name: 'Collections type'
siteSettings:
  1047e869-8b80-481b-bc87-ce5d9212ed20: # En
    hasUrls: true
    template: null
    uriFormat: 'collections-type/{slug}'
structure:
  maxLevels: null
  uid: 5a17098a-46c0-4e3f-bbd6-58d3d45bc62a
