defaultPlacement: end
fieldLayouts:
  9a3b4fb4-799d-4f4b-92a7-04a5fa47fef9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: f0295ea2-40c1-4a94-883f-cdea50022fcc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f7ea6ac1-0d91-4a9d-8335-52189cdbf742
        userCondition: null
handle: productType
name: 'Product type'
siteSettings:
  1047e869-8b80-481b-bc87-ce5d9212ed20: # En
    hasUrls: true
    template: null
    uriFormat: 'product-type/{slug}'
structure:
  maxLevels: null
  uid: 4afc3cfb-83c7-4315-8d7c-976a894c9dab
