childBlocks: null
conditions:
  craft\elements\Category:
    class: craft\elements\conditions\categories\CategoryCondition
    conditionRules:
      -
        class: craft\elements\conditions\categories\GroupConditionRule
        operator: ni
        uid: 991302b4-ff42-403b-b393-189374244655
        values:
          - ba5b7401-275f-4952-92bb-3565a2ee93ae # Industry
          - 9d8f857d-348e-43fb-9987-914354d04ac1 # Project type
          - 75febb45-c75f-4d73-842b-63c42bc30f17 # Technology
    elementType: craft\elements\Category
    fieldContext: global
  craft\elements\Entry:
    class: craft\elements\conditions\entries\EntryCondition
    conditionRules:
      -
        class: craft\elements\conditions\entries\TypeConditionRule
        operator: in
        uid: 7b740eb5-9ab7-4c53-9ac4-6d0de337d184
        values:
          - 7c9ee3eb-515b-4916-a37b-dc67ed2302e6
    elementType: craft\elements\Entry
    fieldContext: global
description: 'Generate tags from case categories'
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  a4a462ab-3d14-41bf-8afb-9a3182356f5c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Tags will be automatically fetched from the categories of the current case'
            type: craft\fieldlayoutelements\Tip
            uid: 682c9764-ebc2-477a-94a3-cdf0309d67e4
            userCondition: null
        name: Default
        uid: 6d9a71a1-8062-485c-9130-e34fbc8fd868
        userCondition: null
group: 6cf02784-36ae-41ab-adbd-a984ca016b7a # Column content
groupChildBlockTypes: true
handle: automaticTags
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Automatic tags'
sortOrder: 21
topLevel: false
