childBlocks: null
conditions:
  craft\elements\Category:
    class: craft\elements\conditions\categories\CategoryCondition
    conditionRules:
      -
        class: craft\elements\conditions\categories\GroupConditionRule
        operator: ni
        uid: de66396c-b4ed-44d8-a9c1-9804dafc9817
        values:
          - ba5b7401-275f-4952-92bb-3565a2ee93ae # Industry
          - 9d8f857d-348e-43fb-9987-914354d04ac1 # Project type
          - 75febb45-c75f-4d73-842b-63c42bc30f17 # Technology
    elementType: craft\elements\Category
    fieldContext: global
  craft\elements\Entry:
    class: craft\elements\conditions\entries\EntryCondition
    conditionRules:
      -
        class: craft\elements\conditions\entries\TypeConditionRule
        operator: ni
        uid: d5c2deb9-4217-45a6-b410-e8b781e57a3d
    elementType: craft\elements\Entry
    fieldContext: global
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  f286da70-8d2b-4aaf-b1cc-d4dce700a3e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3bf5b502-7f7c-4b98-8bfb-ae375ae4684b
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b133a20a-3f13-4502-a275-beb82db2dff7
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 2e956f7d-1851-40a0-b05e-90c4fb05309a
        userCondition: null
group: 6cf02784-36ae-41ab-adbd-a984ca016b7a # Column content
groupChildBlockTypes: true
handle: awards
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Awards
sortOrder: 25
topLevel: false
