childBlocks: null
conditions:
  craft\elements\Category:
    class: craft\elements\conditions\categories\CategoryCondition
    conditionRules:
      -
        class: craft\elements\conditions\categories\GroupConditionRule
        operator: ni
        uid: a639a755-2b30-46c4-9dde-dfbc5386bab9
        values:
          - ba5b7401-275f-4952-92bb-3565a2ee93ae # Industry
          - 9d8f857d-348e-43fb-9987-914354d04ac1 # Project type
          - 75febb45-c75f-4d73-842b-63c42bc30f17 # Technology
    elementType: craft\elements\Category
    fieldContext: global
  craft\elements\Entry:
    class: craft\elements\conditions\entries\EntryCondition
    conditionRules:
      -
        class: craft\elements\conditions\entries\TypeConditionRule
        operator: ni
        uid: 2fdb8b13-6bfa-4bae-bdf6-5daf714d5cbe
    elementType: craft\elements\Entry
    fieldContext: global
description: 'Carousel element'
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  ff76e5aa-385b-4570-8643-0bb5aeae0691:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3d0a153d-7cf3-4fd2-a96a-ca47645e79df
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb23f7be-e89d-4106-a5fc-55546663ee73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ce0d561-b653-4fac-ad89-cfc3ada863c6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1a4a1bf-faf4-40e8-952a-a33fae0239db
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 62414f93-9b24-4a37-a176-517a89750fa5
        userCondition: null
group: de9d2109-ce8f-4710-b27c-9a2d6be8fc0b # Row content
groupChildBlockTypes: false
handle: carousel
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Carousel
sortOrder: 10
topLevel: false
