childBlocks:
  - nestedRow
  - newsletter
  - customMessage
  - icons
  - text
  - tags
  - automaticTags
  - media
  - entry
  - awards
  - fatAssHeadline
  - arrowLinks
  - profile
conditions: null
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  fb112a0f-bfcb-4138-baae-19a597243907:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 1c3d746e-b097-4eee-a4cc-3b960c5b70ed
            userCondition: null
        name: Default
        uid: 3575a9f6-cb1d-4a6e-be4f-402a1b7d6ae9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f51fbca5-c800-46c8-b9a2-c7020383b485 # Width
            instructions: 'The width of the column (-1 will make them fill the available space)'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea705ae5-8dcf-4197-94ef-805a77ab2e33
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bb5f9e4-c6c5-4644-9cec-aa10eb443829 # Width - mobile
            instructions: 'The width of the column, on mobile'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd2a9805-24a7-4d82-b2cd-1bf9b1a74acb
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: 70d60b55-9a27-406c-889c-98a65758bf82
        userCondition: null
group: de9d2109-ce8f-4710-b27c-9a2d6be8fc0b # Row content
groupChildBlockTypes: false
handle: column
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 4
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Column
sortOrder: 6
topLevel: false
