childBlocks: null
conditions: null
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  28bc2060-9baa-4162-b360-12cb191d4cee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Coming soon data coming from Globals'
            type: craft\fieldlayoutelements\Tip
            uid: 03f4e6cd-b43c-4a4e-86ab-945cdcb6505d
            userCondition: null
        name: Default
        uid: ca4538b5-6eef-41fe-8609-878fcc3385ed
        userCondition: null
group: de9d2109-ce8f-4710-b27c-9a2d6be8fc0b # Row content
groupChildBlockTypes: true
handle: comingSoon
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Coming soon'
sortOrder: 12
topLevel: false
