childBlocks: null
conditions: null
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  d9130c05-6954-489f-a634-b2e67dcc1f64:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5f97da99-2152-4c3f-88e2-2c51f5edfad4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f854ae7-c2d2-40a4-bc3c-954651f762f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 410758fc-ab24-44cb-8e07-4508edca4dcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 478723c1-0ea2-4d2a-9640-07b2ac58cd30
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: ac9bd438-e3ac-46d2-93eb-cd7ff5325c88
        userCondition: null
group: 6cf02784-36ae-41ab-adbd-a984ca016b7a # Column content
groupChildBlockTypes: true
handle: contentLink
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Content Link'
sortOrder: 22
topLevel: false
