childBlocks: null
conditions: null
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  3b444bbc-e0ff-4910-9e19-41133ce81093:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4ce0d561-b653-4fac-ad89-cfc3ada863c6
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a259812-de22-4096-9768-b7006e0000f9
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 837ba012-c266-43a7-97c8-4af883700af7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f51fbca5-c800-46c8-b9a2-c7020383b485 # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7dcb60c7-aecb-4651-9a19-e78885cefc98
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 095b1ba0-e13e-4ee0-a4c3-7956726a1798
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61b0e2ba-1a71-4c83-95fa-22f99f10e786
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9cf21d71-c667-4789-911d-bdd341a4aabd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a337a358-b56e-402c-94a7-7ce659cdb55d
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: b41ab111-3f12-49fe-85b6-73c4d9739260
        userCondition: null
group: 6cf02784-36ae-41ab-adbd-a984ca016b7a # Column content
groupChildBlockTypes: true
handle: entry
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Entry
sortOrder: 24
topLevel: false
