childBlocks: null
conditions:
  craft\elements\Category:
    class: craft\elements\conditions\categories\CategoryCondition
    conditionRules:
      -
        class: craft\elements\conditions\categories\GroupConditionRule
        operator: ni
        uid: 74bdacf6-5fff-48ea-9154-90c98c434c75
        values:
          - ba5b7401-275f-4952-92bb-3565a2ee93ae # Industry
          - 9d8f857d-348e-43fb-9987-914354d04ac1 # Project type
          - 75febb45-c75f-4d73-842b-63c42bc30f17 # Technology
    elementType: craft\elements\Category
    fieldContext: global
  craft\elements\Entry:
    class: craft\elements\conditions\entries\EntryCondition
    conditionRules:
      -
        class: craft\elements\conditions\entries\TypeConditionRule
        operator: ni
        uid: 1183ff23-4e37-4b28-89ea-2d2fd86c1e6c
    elementType: craft\elements\Entry
    fieldContext: global
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  4bf12be8-74c7-48be-bde0-942417133870:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: eef8323c-7240-4246-be5b-6cc0dd6891e6 # Trumpet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c047a65-92ce-4947-b184-34383b6dc556
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d0a153d-7cf3-4fd2-a96a-ca47645e79df
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d9c77d5-38d9-4bc6-afc2-4eed821b16be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1a2d1de-6ac9-465b-a412-a5942eb2dc3c
            instructions: 'Make the headline proper fat'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 436e924f-2c73-4d91-8ff3-eab6b2a3c8b6
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 5f9cdd58-5b59-4a1c-a349-41ee47514d04
        userCondition: null
group: 6cf02784-36ae-41ab-adbd-a984ca016b7a # Column content
groupChildBlockTypes: true
handle: fatAssHeadline
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Fat ass headline'
sortOrder: 26
topLevel: false
