childBlocks:
  - overlayedItem
conditions:
  craft\elements\Category:
    class: craft\elements\conditions\categories\CategoryCondition
    conditionRules:
      -
        class: craft\elements\conditions\categories\GroupConditionRule
        operator: ni
        uid: 92bcdc40-222e-48ea-8178-0e5d983f09d2
        values:
          - ba5b7401-275f-4952-92bb-3565a2ee93ae # Industry
          - 9d8f857d-348e-43fb-9987-914354d04ac1 # Project type
          - 75febb45-c75f-4d73-842b-63c42bc30f17 # Technology
    elementType: craft\elements\Category
    fieldContext: global
  craft\elements\Entry:
    class: craft\elements\conditions\entries\EntryCondition
    conditionRules:
      -
        class: craft\elements\conditions\entries\TypeConditionRule
        operator: ni
        uid: 9a5cb234-a6e5-407a-ae78-fb84d647211f
    elementType: craft\elements\Entry
    fieldContext: global
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  3993e30c-54b0-4519-a622-b91ee47bf89c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: eef8323c-7240-4246-be5b-6cc0dd6891e6 # Trumpet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a82bee4-4173-4d3a-819f-e5d4a704f683
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d0a153d-7cf3-4fd2-a96a-ca47645e79df
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c105f3c-2872-48ec-8bb5-281c6baaea4f
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: a1a2d1de-6ac9-465b-a412-a5942eb2dc3c
            instructions: null
            label: 'Moving headline'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f8bf543-6f28-4d99-8a4a-7874c1a78845
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5f97da99-2152-4c3f-88e2-2c51f5edfad4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e52e7af-b8b4-4b34-bd21-2f9d0caef095
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 410758fc-ab24-44cb-8e07-4508edca4dcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 958c84bf-b218-477b-a36d-fc61c85ec6bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ce0d561-b653-4fac-ad89-cfc3ada863c6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 232706f8-9e97-4ca8-a888-af950a7f0911
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: b0cba36b-8645-4e8e-a926-34109c8a8ac6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7f80d9a6-6940-4531-8c59-9ed427fef9e1 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cfc1716-99b6-4948-b49e-9d94c3e61b0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: cec5bab9-7c4c-48b3-9bcb-08dbb06d23f9
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3b7ccd03-b55f-4410-9712-1a9f5610aa54
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a85f8e3d-3eee-48ba-b593-baffffe96f97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e2bd9e0-e192-495f-b8be-b0c531bda0f8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11509a54-1cfd-491f-aa64-f7cb3a7f17d1
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 0804343b-d7ec-48a8-9850-0af62156441d
        userCondition: null
group: null
groupChildBlockTypes: false
handle: heroContent
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Hero - content'
sortOrder: 2
topLevel: true
