childBlocks: null
conditions: null
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  bf90bf01-0bdd-40e1-8467-e1422173f561:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: eef8323c-7240-4246-be5b-6cc0dd6891e6 # Trumpet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2cf5875-ca8a-45dd-81a3-c25d22cf3091
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d0a153d-7cf3-4fd2-a96a-ca47645e79df
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e31536a-f5a6-42a4-8663-6d412d3fe5dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8dc1d25a-3e67-40c0-9cc6-661f8ec49d84
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bffa618-e565-4818-803d-abff58b698f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c674294c-e7e1-4641-bfb4-94d43f175a06
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c61cbd88-7789-465e-abd7-023896a22eb3
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: e7699bd1-2fe4-456b-b707-bd2d82c58a95
        userCondition: null
group: de9d2109-ce8f-4710-b27c-9a2d6be8fc0b # Row content
groupChildBlockTypes: true
handle: heroImageV2
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Hero - Image v2'
sortOrder: 8
topLevel: false
