childBlocks: null
conditions:
  craft\elements\Category:
    class: craft\elements\conditions\categories\CategoryCondition
    conditionRules:
      -
        class: craft\elements\conditions\categories\GroupConditionRule
        operator: ni
        uid: 32765e79-85a4-4133-84b5-80ca0009a7d2
        values:
          - ba5b7401-275f-4952-92bb-3565a2ee93ae # Industry
          - 9d8f857d-348e-43fb-9987-914354d04ac1 # Project type
          - 75febb45-c75f-4d73-842b-63c42bc30f17 # Technology
    elementType: craft\elements\Category
    fieldContext: global
  craft\elements\Entry:
    class: craft\elements\conditions\entries\EntryCondition
    conditionRules:
      -
        class: craft\elements\conditions\entries\TypeConditionRule
        operator: ni
        uid: 0065997f-22e8-4006-9cc9-25d89eadfda6
    elementType: craft\elements\Entry
    fieldContext: global
description: 'icons module '
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  d1a5bbf0-2d70-4696-9c8e-5f1736fc309d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6f9a4073-8da2-4ca3-bbab-b6fc385a8965
            instructions: 'Select desired icons to show on your section'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e2f9ba1-719a-49ee-98d2-f40243bebb42
            userCondition: null
            warning: null
            width: 100
        name: Icons
        uid: 9f4ef3f7-a584-45e1-9b54-32fbfd1ddd3b
        userCondition: null
group: 6cf02784-36ae-41ab-adbd-a984ca016b7a # Column content
groupChildBlockTypes: true
handle: icons
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Icons
sortOrder: 18
topLevel: false
