childBlocks: null
conditions: null
description: null
enabled: true
field: 4e5308e5-8f1f-4b51-8db8-a2d705288508
fieldLayouts:
  6a705f79-4af8-453d-a15c-1aed2b196393:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7f80d9a6-6940-4531-8c59-9ed427fef9e1 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ee57577-d3c2-4b8a-aacd-9a81e406cfd7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d0a153d-7cf3-4fd2-a96a-ca47645e79df
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2da15590-07d8-4438-a73a-906b112d0f76
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ad52ea7e-f516-4e0f-b085-4d63b3364d28 # Typed field link list
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf7c1916-f78d-47bc-9061-dda13778f459
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 9ab51193-3ffe-4690-a6d0-74dabd59be00
        userCondition: null
group: null
groupChildBlockTypes: true
handle: item
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Coming soon'
sortOrder: 1
topLevel: true
