childBlocks: null
conditions: null
description: ''
enabled: true
field: 91a991d3-fdec-4366-ab5a-78cacba3eba7
fieldLayouts:
  a4880aa8-df21-469e-8a55-fea3b6f581c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6f9a4073-8da2-4ca3-bbab-b6fc385a8965
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef8d2805-46ff-447d-b524-2230bcd5cad0
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: c5e698c7-fe97-45b1-bb77-a20b75518ce0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c674294c-e7e1-4641-bfb4-94d43f175a06
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dd6e68e-d1a3-4d42-9057-c20ce2911f29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bb5f9e4-c6c5-4644-9cec-aa10eb443829 # Width - mobile
            instructions: 'The width of the media, on mobile'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36e6ebf4-f5ec-40ba-a8ac-0f1639325ec6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbf998fa-9b85-4d81-8836-6949a83a7587
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23536e85-3f57-4456-bab0-4816c92f82c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ef15c05-012a-4131-b0da-670af6ff8e32
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2109054-f97b-4fda-802d-ec9a573e2906
            userCondition: null
            warning: null
            width: 100
        name: Mobile
        uid: 97408606-f445-49f9-98c2-8dc0cd7ecdf3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f51fbca5-c800-46c8-b9a2-c7020383b485 # Width
            instructions: 'The width of the media, inside its containing column.'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8b4331e-2b3f-4057-9c6b-9069e935ceb8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 095b1ba0-e13e-4ee0-a4c3-7956726a1798
            instructions: 'When Media width is less then Column width, it can be aligned inside the column'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfcea688-1e9d-4211-af8d-845bb5c99d84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b7ccd03-b55f-4410-9712-1a9f5610aa54
            instructions: 'Margins pushes the media up of down. Negative margin pulls the media up and down (creates overlap)'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3bceb2b-4e3f-4fc9-9a98-2d5a5387f665
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e2bd9e0-e192-495f-b8be-b0c531bda0f8
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2dcd252-9fb2-439f-a5e7-e4ec8b2437b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea0487cd-a8da-457b-b08e-e2deac37bb38
            instructions: 'A negative parallax makes the media move slower than the scroll speed'
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 133c6398-79d4-4f7b-adef-9f6b29744b95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bd5cb7a7-8349-4f61-82bf-a94c800e05c5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f84b4436-b214-4df1-a42e-625ffa3bd67a
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: c5f91741-4b6d-4312-9b0b-a63206757e0c
        userCondition: null
group: 6cf02784-36ae-41ab-adbd-a984ca016b7a # Column content
groupChildBlockTypes: true
handle: media
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Media
sortOrder: 23
topLevel: false
