columnSuffix: null
contentColumnType: string
fieldGroup: 4c60465d-56ea-4e52-83bb-57923cc97458 # Common
handle: categoryType
instructions: null
name: 'Category type'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:e9fe8b41-42b3-4d30-b05d-a4ffeb5d3b79' # Product type
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
