columnSuffix: uyhglabl
contentColumnType: datetime
fieldGroup: 4c60465d-56ea-4e52-83bb-57923cc97458 # Common
handle: date2
instructions: null
name: 'Date 2'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
