columnSuffix: null
contentColumnType: string
fieldGroup: 4c60465d-56ea-4e52-83bb-57923cc97458 # Common
handle: pageModules
instructions: null
name: 'Page Modules'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagemodules}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
