columnSuffix: null
contentColumnType: string
fieldGroup: 4c050537-070e-4953-b986-9b6e8903e049 # Products
handle: productWeight
instructions: null
name: 'Product weight'
searchable: false
settings:
  contentTable: '{{%matrixcontent_productweight}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
