columnSuffix: otsmmrkd
contentColumnType: mediumtext
fieldGroup: 4c050537-070e-4953-b986-9b6e8903e049 # Products
handle: productJsonData
instructions: null
name: 'Product Json Data'
searchable: false
settings:
  availableLanguages:
    - json
  codeFolding: true
  columnType: mediumtext
  defaultValue: ''
  fontSize: 14
  language: json
  lineNumbers: true
  monacoEditorOptions: ''
  placeholder: ''
  showLanguageDropdown: false
  singleLineEditor: false
  theme: auto
translationKeyFormat: null
translationMethod: none
type: nystudio107\codefield\fields\Code
