columnSuffix: null
contentColumnType: string
fieldGroup: 4c050537-070e-4953-b986-9b6e8903e049 # Products
handle: productTags
instructions: null
name: 'Product tags'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'taggroup:58a8e029-3d0d-4160-bbca-f83377b84b6d' # Entry type
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
