columnSuffix: rhavmhuc
contentColumnType: text
fieldGroup: db292b46-b1e0-4cad-bfa6-c5aba283fd39 # Products
handle: productJsonData
instructions: null
name: 'JSON Data'
searchable: false
settings:
  availableLanguages:
    - css
    - graphql
    - html
    - javascript
    - json
    - markdown
    - mysql
    - php
    - shell
    - twig
    - typescript
    - yaml
  codeFolding: false
  columnType: text
  defaultValue: ''
  fontSize: 14
  language: javascript
  lineNumbers: false
  monacoEditorOptions: ''
  placeholder: ''
  showLanguageDropdown: true
  singleLineEditor: false
  theme: auto
translationKeyFormat: null
translationMethod: none
type: nystudio107\codefield\fields\Code
