columnSuffix: rqfnnnzd
contentColumnType: text
fieldGroup: 4c050537-070e-4953-b986-9b6e8903e049 # Products
handle: shopifyId
instructions: null
name: 'Shopify Id'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
