columnSuffix: pvbjdlew
contentColumnType: text
fieldGroup: 4c60465d-56ea-4e52-83bb-57923cc97458 # Common
handle: text
instructions: null
name: Text
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
