columnSuffix: oqikovdt
contentColumnType: text
fieldGroup: 4c60465d-56ea-4e52-83bb-57923cc97458 # Common
handle: textLimited
instructions: 'Limited to 360 characters'
name: 'Text - limited'
searchable: false
settings:
  byteLimit: null
  charLimit: 360
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
