columnSuffix: null
contentColumnType: string
fieldGroup: 57718d4c-9468-4391-92f0-3deab64fa3d5 # Common
handle: theme
instructions: null
name: Theme
searchable: false
settings:
  contentTable: '{{%matrixcontent_theme}}'
  maxBlocks: 1
  minBlocks: 0
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
