columnSuffix: qykjkfkn
contentColumnType: text
fieldGroup: fd82bfdf-232c-46a8-baba-d5e47c5bcf07 # Layout
handle: translateY
instructions: null
name: 'Translate Y'
searchable: false
settings:
  initialRows: 8
  options: "min: -100,\r\nmax: 100,\r\nfrom: 0,\r\ngrid: true,\r\nprefix: \"translateY(\",\r\npostfix: \"%)\",\r\nhide_min_max: true,\r\nskin: \"round\"\r\n"
translationKeyFormat: null
translationMethod: none
type: lewisjenkins\craftrangeslider\fields\RangeSlider
