columnSuffix: plfaalcc
contentColumnType: text
fieldGroup: 57718d4c-9468-4391-92f0-3deab64fa3d5 # Common
handle: trumpet
instructions: null
name: Trumpet
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
