columnSuffix: null
contentColumnType: string
fieldGroup: 57718d4c-9468-4391-92f0-3deab64fa3d5 # Common
handle: typedFieldLinkList
instructions: null
name: 'Typed field link list'
searchable: false
settings:
  contentTable: '{{%matrixcontent_typedfieldlinklist}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
