columnSuffix: null
contentColumnType: string
fieldGroup: 57718d4c-9468-4391-92f0-3deab64fa3d5 # Common
handle: widget
instructions: null
name: Widget
searchable: false
settings:
  contentTable: '{{%matrixcontent_widget}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
