columnSuffix: abqthvdl
contentColumnType: text
fieldGroup: fd82bfdf-232c-46a8-baba-d5e47c5bcf07 # Layout
handle: widthMobile
instructions: null
name: 'Width - mobile'
searchable: false
settings:
  initialRows: 8
  options: "grid: true,\r\nvalues: [\"auto\", 1, 2, 3, 4, 5, 6, \"fullscreen\"],\r\nfrom: 0,\r\nprefix: \"Columns: \",\r\nhide_min_max: true,\r\ngrid_num: 8,\r\nskin: \"round\""
translationKeyFormat: null
translationMethod: none
type: lewisjenkins\craftrangeslider\fields\RangeSlider
