columnSuffix: kezyfynj
contentColumnType: text
fieldGroup: fd82bfdf-232c-46a8-baba-d5e47c5bcf07 # Layout
handle: width
instructions: 'Leave at -1 to follow content flow'
name: Width
searchable: false
settings:
  initialRows: 8
  options: "grid: true,\r\nvalues: [\"auto\", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, \"fullscreen\"],\r\nfrom: 0,\r\nprefix: \"Columns: \",\r\nhide_min_max: true,\r\ngrid_num: 14,\r\nskin: \"round\""
translationKeyFormat: null
translationMethod: none
type: lewisjenkins\craftrangeslider\fields\RangeSlider
