dateModified: 1710166656
elementSources:
  craft\elements\Category:
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'group:e9fe8b41-42b3-4d30-b05d-a4ffeb5d3b79'
      tableAttributes:
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'group:78a10a73-3307-4664-a775-57f44bee7c16'
      tableAttributes:
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'group:4817083b-df5e-4f7f-9a71-10133472f314'
      tableAttributes:
        - link
      type: native
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:128e704b-a4ec-4a7f-9267-637db9630924'
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
email:
  fromEmail: dev@springsummer.dk
  fromName: 'Bella Donna'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  '':
    name: 'Product Fields'
  9e615391-8b9d-42cc-ad8b-f93ed9276260: # Products
    name: Products
  db292b46-b1e0-4cad-bfa6-c5aba283fd39: # Products
    name: Products
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: '@webroot/media'
    type: craft\fs\Local
    url: '@assetUrl'
meta:
  __names__:
    0eb6c413-07d2-4737-be17-ec53e88584b8: Link # Link
    1b783c4f-bd80-401c-b377-8dcaaf0ffb68: Media # Media
    1c06b984-b507-4166-99c2-23e7ccbd2b42: 'Custom Shopify' # Custom Shopify
    01c27f3d-48f7-4759-8491-63fda533f8ed: 'Image Teaser' # Image Teaser
    1fbc15c7-66c7-41c0-8659-3be4bcdf27f7: 'Product description' # Product description
    2c701826-3564-4d29-b1f0-3b011f8e76f3: Products # Products
    2d19b980-c6d5-4ec4-bba9-b6987c7e9611: Content # Content
    3b329d09-0244-4772-a51f-a0707022c5b3: 'All Offers & Packages' # All Offers & Packages
    3fbdccf5-3d82-4362-b9d8-d8e273a38564: 'Tag left' # Tag left
    4a63451e-1c46-4b2b-89ae-df07b8630665: Items # Items
    4ecfe397-4ca6-47b9-9f2d-c3824f83224b: 'Entry Carousel' # Entry Carousel
    5a80ea5c-f947-42c7-9277-e40e987a0ce3: Link # Link
    5be45e90-7120-4be5-a6a7-841579642fa6: Headline # Headline
    5d2e71c7-1df7-4268-855a-c1bf35dba93b: Bullets # Bullets
    5e312397-a325-4667-b1f0-9aecd9495873: 'Responsive media' # Responsive media
    5f3c423f-e4c6-4473-b33a-eb57f84dd166: Items # Items
    5f68dae6-585b-4e9c-bf37-2133a3cc3fa7: 'All News & Events' # All News & Events
    6aad1b54-699a-4b2a-abad-d60f90f87b97: Info # Info
    6d3f513b-f0f6-411b-8b54-070e684dda04: 'Show image caption' # Show image caption
    6e87e440-9e69-40cf-a621-a73cfdbf3cf2: Items # Items
    6ef9cec9-a33d-44ba-bfc0-4aafd2505bdc: 'Text color' # Text color
    7f9e33e7-9f68-483f-8eab-d649a71e0286: 'Show image captions' # Show image captions
    07fedf19-0946-4fea-abb7-bbf308f9e2e7: Headline # Headline
    9e615391-8b9d-42cc-ad8b-f93ed9276260: Products # Products
    13e567bf-f8ac-4de9-8914-30745f6bc860: Entry # Entry
    18c89f89-fdb8-40ce-8823-04181e63dd81: Default # Default
    24ae792c-53e5-48b1-9d46-7e1af52c6c31: Right # Right
    30c68743-dafc-4323-94f9-4b28cb27d8fc: Entry # Entry
    31a60245-d9ed-46e7-a661-d55f83c47300: Text # Text
    32bce18a-1429-4689-9c7f-c751aa890060: Media # Media
    32d8d8a3-0d3d-4d41-8ad9-f8812acda8d7: Content # Content
    32e79432-b3f7-4ed8-8ebe-a7a2f6e365f1: Media # Media
    33bf4874-1ebd-4802-b260-a99714519a9d: Items # Items
    36cdc76b-4a86-481f-baf5-8f4f42ca738b: Columns # Columns
    37d934a7-712d-4c75-babf-32f3ba2a5688: Media # Media
    37efb20f-88a2-4020-ab19-9d65725f7067: 'Dual Teaser' # Dual Teaser
    68dd7f73-3c5f-4a60-acf5-4259d9c4f8d4: Products # Products
    69adfdd0-6999-4c8d-974e-28568949ec8d: 'Page Hero' # Page Hero
    71b524a9-c436-43e2-992e-9b971fe665a0: Text # Text
    78a6528a-68b2-4a8a-b99e-d3992ed9b750: Link # Link
    92f30535-adcc-4f9f-b5b1-60042746f6c5: Textfield # Textfield
    94ebaded-b5da-4f03-bf51-baf58f377899: 'JSON Data' # JSON Data
    127fb155-166e-4996-bbfe-a130373c57ff: Link # Link
    198d065e-729a-42ed-a34a-438ac25b88e6: Tag # Tag
    202c7458-1c92-4184-ba71-3ed53b632500: Tag # Tag
    308a8186-e506-473b-99f4-64f96e0794ac: 'Tag right' # Tag right
    389d1cf4-6734-4c9e-a005-6fc552ca5dbb: Richtext # Richtext
    510cea0e-aa20-43e0-80a2-af40fb596356: Headline # Headline
    520f8c9d-df73-4870-b6b7-84ef848fe18e: Headline # Headline
    620e8bdf-2551-4e90-abfc-4ec607565261: 'All Press' # All Press
    875ddcb2-5ebb-4e5c-b2e8-df2b8d16d467: 'Rooms Carousel' # Rooms Carousel
    896fd6fd-26d2-4480-b641-acfa5a037eb1: Headline # Headline
    1047e869-8b80-481b-bc87-ce5d9212ed20: En # En
    6767a8c2-9e70-403f-894c-db67293a9518: Link # Link
    8554cfab-f0ff-4325-af7c-d57d02af800b: 'Custom link' # Custom link
    9558a12f-f2c0-400d-bade-e256dded714f: List # List
    041511d7-bee4-4cef-8292-19024a001bd3: Entries # Entries
    45747ae3-7ff5-4f53-a00a-776b00d906da: 'Show image caption' # Show image caption
    68843b40-25df-4563-aeb5-8dfca909747b: Tag # Tag
    660741d0-fd1a-4698-931a-09df2c3cc616: Headline # Headline
    2413398d-e673-4cc4-b977-982ab8860b2d: Headline # Headline
    3919271a-0c9b-44c9-aeb7-4e89acba93e5: Warning # Warning
    a048f70f-0e8a-4aef-9458-80a75f337a8b: Reversed # Reversed
    a3b80282-c227-4b0e-80bb-13fb9c524a9c: Item # Item
    a4df4597-7f09-4358-8460-d357905a981d: Media # Media
    a7ca077f-a851-432a-8c7b-7147f9a892c9: 'Custom link' # Custom link
    a56ab205-61a5-4deb-8aa8-61a61a329675: Items # Items
    a8227c69-063e-45e4-821b-858e1de4dfe9: Image # Image
    a2754926-d09b-4f83-aefe-501d934e71d4: Closable # Closable
    add8265c-3aeb-4a66-ac9c-a82af78abf31: Link # Link
    b2d1f2c3-d934-48e6-ab30-a27468acbeaa: 'Fullscreen media' # Fullscreen media
    b8d154ec-090b-4c58-a4d5-4894e7ccda08: Info # Info
    b935c2a3-8db9-4f83-a0bd-7c1f3b37ba8c: Media # Media
    b27511eb-67e1-4b84-a3bb-9966c1284964: Icon # Icon
    b5505176-4e5c-437b-a949-83381822d12e: Tag # Tag
    be6f80ce-90c7-47f2-9c12-08a22648cae9: Tag # Tag
    bfe689ab-f4c8-4ca9-8150-b56e193158e4: Layout # Layout
    c1e40e15-2241-4142-9b1b-bdf8f9855cd6: Reversed # Reversed
    c2d23e62-72de-4fbb-905d-e7ea3be9a518: 'Rooms grid' # Rooms grid
    c3f25b5c-f50f-4aee-9029-b1d9ef32e647: Link # Link
    c3fe577b-c14c-4b22-9306-7251cc97de1f: Tag # Tag
    c25c4da9-00c6-4de5-87e2-096c18dd3201: Item # Item
    cd225b7f-272f-4081-9a0c-88749790b513: Entries # Entries
    cfeaf304-9265-4c87-9d94-a8c7a1f39a45: 'Card Carousel' # Card Carousel
    d7de5b41-d9f2-4ef8-82b7-aec59f8ac554: 'Shopify Id' # Shopify Id
    d8f882ec-fc67-4e36-be86-d7a19aa8d447: Left # Left
    d12e78b0-196a-4458-8963-0c7e00537f2c: Media # Media
    d749ade5-969e-4d92-9b22-c6b726ae50e8: 'Tag right' # Tag right
    d11934d3-4fcb-4b34-ba2c-ef76aff56d3f: 'JSON Data' # JSON Data
    d22684af-98f1-4efe-8201-c30d64fe7008: 'Shopify Id' # Shopify Id
    db292b46-b1e0-4cad-bfa6-c5aba283fd39: Products # Products
    dd34ba2f-e52f-4af3-a24f-07b7843021b5: Headline # Headline
    de67e196-ad55-4210-8298-5a59eb02bbd9: Warning # Warning
    def7b936-876b-42c4-91aa-0e4217be184f: Default # Default
    e09e8bf3-e3ab-4d22-b8b5-7f0a67bdaba9: Warning # Warning
    e2d09c3d-fd6d-479c-b32a-52667fe689ad: Link # Link
    e7bc80d2-7a8e-4cb6-b565-ea3c4c76d7c6: Medias # Medias
    e9c4dad0-f52e-4755-b53f-99fb71cab0b3: Default # Default
    e31bcbff-2d8f-4e8b-9559-1f3137c16310: Items # Items
    e89ec6e5-3171-41c7-aa77-02b1c3e3ae8e: Headline # Headline
    e564e547-a62d-4ea0-b2cb-f1d3dbe63b30: Headline # Headline
    ee99146c-165d-41c6-a71c-9ee7339a9f5c: 'Product description' # Product description
    f0e439c1-51cf-410f-8375-fdb487d77f76: Text # Text
    f02beb95-b907-40b0-8c52-264aae8a3ca5: 'Homepage Hero' # Homepage Hero
    f4f0da20-3f64-4b4d-9c2d-49916f806b76: Links # Links
    f9fc7333-9e84-4116-9a85-7ce93821b5eb: Gallery # Gallery
    f72ff1e6-b747-4bd1-9d0f-f5bd1afd1987: 'Responsive media' # Responsive media
    f9543ccd-d05f-4090-a67e-7f9e52d218ef: Link # Link
    fb53847b-c206-48b9-8217-e0640beafb74: 'Text Teaser' # Text Teaser
    fbf38450-f32e-4f7d-9241-5db02efbcc29: Info # Info
    fceef115-987b-4f89-9408-e094ab7aa678: 'Tag left' # Tag left
plugins:
  _craft-shopify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  _shopify-wrapper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  _storefront:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "#nav {\r\n    margin-top: 10px;\r\n}\r\n\r\n#nav li a {\r\n    padding-top: 10px;\r\n    padding-left: 10px;\r\n    padding-bottom: 10px;\r\n    padding-right: 10px;\r\n}\r\n\r\n.sidebar nav li a {\r\n    margin-bottom: 5px;\r\n    padding-top: 10px;\r\n    padding-bottom: 10px;\r\n}\r\n\r\n.sidebar .heading>span {\r\n    padding: 0;\r\n}\r\n\r\n#system-info {   \r\n    display: block;\r\n    height: auto;\r\n    background-color: transparent;\r\n    padding: 30px 10px;\r\n}\r\n\r\n#system-info:focus, #system-info:hover {\r\n    background-color: transparent !important;\r\n}\r\n\r\n#site-icon {\r\n    height: auto;\r\n}\r\n\r\n#site-icon img, #site-icon svg {\r\n    height: auto;\r\n    width: auto;\r\n}\r\n\r\n#system-name {\r\n    display: none;\r\n}\r\n\r\n#global-sidebar {\r\n    padding: 8px;\r\n    padding-bottom: 0;\r\n}\r\n\r\n#devmode {\r\n    margin: 0 -8px;\r\n    width: calc(100% + 16px);\r\n}\r\n\r\n#sidebar {\r\n    padding: 0 26px;\r\n}\r\n\r\n.sidebar#sidebar nav {\r\n    padding: 0;\r\n    margin-left: -20px;\r\n    margin-right: -20px;\r\n}\r\n\r\n.sidebar nav {\r\n    padding: 0;\r\n}\r\n\r\nbody.ltr .sidebar nav>ul>li.heading>ul>li>a, body.ltr .sidebar nav>ul>li:not(.heading)>a {\r\n    padding-left: 19px;\r\n}\r\n\r\n#fields-pageModules > .blocks > div:nth-child(odd) {\r\n    border: 1px solid green;\r\n}\r\n\r\n#fields-pageModules > .blocks > div:nth-child(even) {\r\n    border: 1px solid blue;\r\n}\r\n"
      cacheBusting: true
      cssFile: ''
  craft-shopify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: 1SUUMUM453II5WSBARFVYCRD
    schemaVersion: 4.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  ui-element-fields:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Custom Shopify'
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
