changedFieldIndicator: 310713957
field: 36cdc76b-4a86-481f-baf5-8f4f42ca738b # Columns
fieldLayouts:
  ba062cd8-c508-4b2b-a4b4-3e387e84a9ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d8f882ec-fc67-4e36-be86-d7a19aa8d447 # Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1710e61-ba52-40f7-83b0-f7d432530bf0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 24ae792c-53e5-48b1-9d46-7e1af52c6c31 # Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c319408-dfc2-4f8c-ac14-2b0ad9545aba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9dce475e-8cc3-4bae-9862-5228b67903b7
        userCondition: null
fields:
  24ae792c-53e5-48b1-9d46-7e1af52c6c31: # Right
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: right
    instructions: null
    name: Right
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - video
      branchLimit: null
      defaultUploadLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 2
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d8f882ec-fc67-4e36-be86-d7a19aa8d447: # Left
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: left
    instructions: null
    name: Left
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - video
      branchLimit: null
      defaultUploadLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 2
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:def7b936-876b-42c4-91aa-0e4217be184f' # Default
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
