changedFieldIndicator: 1481676554
field: 1b3ced80-d494-4276-8d44-d803ccf02df0
fieldLayouts:
  b469f3fd-c6a0-457d-9c67-846d2a78351e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ccae5132-f702-43d5-b5f4-c517929cf927 # Text color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86e020fa-349d-4746-be8e-1f19e08c4a7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d98acc5c-84e1-47ec-9876-9e0ffcbbb78e # Background color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27f0a891-987d-4162-a8a4-3087bbcc7050
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00ffb3bd-e855-450d-a1f4-42f1848ea0f0
        userCondition: null
fields:
  ccae5132-f702-43d5-b5f4-c517929cf927: # Text color
    columnSuffix: ytoowbjf
    contentColumnType: text
    fieldGroup: null
    handle: textColor
    instructions: null
    name: 'Text color'
    searchable: false
    settings:
      allowCustomColor: true
      allowCustomColorPicker: true
      allowOpacity: true
      colorFormat: hashhex
      defaultColorHandle: black
      defaultOpacity: 100
      fieldDescriptions: false
      paletteBaseColors:
        - black
      paletteColors: ''
      presetId: ''
      presetMode: false
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\colorit\fields\ColoritField
  d98acc5c-84e1-47ec-9876-9e0ffcbbb78e: # Background color
    columnSuffix: ghdrmyxf
    contentColumnType: text
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Background color'
    searchable: false
    settings:
      allowCustomColor: true
      allowCustomColorPicker: true
      allowOpacity: true
      colorFormat: auto
      defaultColorHandle: white
      defaultOpacity: 100
      fieldDescriptions: false
      paletteBaseColors:
        - white
      paletteColors: ''
      presetId: ''
      presetMode: false
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\colorit\fields\ColoritField
