fieldLayouts:
  0b6fde30-814d-4add-9868-0c65f10899ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3d0a153d-7cf3-4fd2-a96a-ca47645e79df
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46593b3c-aa37-42ab-a830-9247e1b6c64a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f9a4073-8da2-4ca3-bbab-b6fc385a8965
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 186cfd56-6053-4599-be5b-56a641b15306
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f97da99-2152-4c3f-88e2-2c51f5edfad4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c1fa8fe-010a-4231-9a14-a5cd2b4abec1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 410758fc-ab24-44cb-8e07-4508edca4dcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2322208-792b-40ee-a05d-e51893f7ee3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d8bdbb5c-69e8-4b97-878a-d7236137f336
            userCondition: null
          -
            elementCondition: null
            fieldUid: 42c1bf8b-0b3b-4afd-9a7d-7208ee253e9c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbbb7412-91b7-45bd-9cd9-4c1d5ed5fdcb
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 087fc117-9bb6-41aa-95c7-4f4b8e445bc1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a23b649c-0d4f-4108-9164-65c931a37763 # Widget
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeadc2eb-8d34-486a-bd2e-7898967101bf
            userCondition: null
            warning: null
            width: 100
        name: Widget
        uid: 728d549a-5a57-4ff1-86b4-28ba6cb5e668
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7f80d9a6-6940-4531-8c59-9ed427fef9e1 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f454f2fb-e1fb-4b7e-a4e2-10d7af6bd66c
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 02981d5f-9239-4b10-8cd0-4ad84c5abdbb
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
