fieldLayouts:
  9f9d264c-9e3b-4d8e-9e29-7f457eee4f03:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Home page link asset'
            type: craft\fieldlayoutelements\Heading
            uid: 2b77bb19-a26d-4798-bec6-11b4fa747882
            userCondition: null
          -
            elementCondition: null
            fieldUid: 6f9a4073-8da2-4ca3-bbab-b6fc385a8965
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e385095d-f677-4398-85af-89ac7fa55a09
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Home page link text'
            type: craft\fieldlayoutelements\Heading
            uid: 4ab58da4-42ec-4cdf-82a2-3e28f1643cf0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 32d5b2cd-e8c9-48ab-b9a0-3ffda7745a4c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e96d082-8b8f-4aad-ae12-a5e0b69fcf2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a8f111bb-4d6d-4c0d-9359-3b6f5b3f17d4
        userCondition: null
handle: header
name: Header
sortOrder: 1
