fieldLayouts:
  0d2114d7-690b-46f2-bb76-a6858cede079:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 10e24b1b-fb07-4d78-b55c-c71b9af6c162
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 144059b9-0f0d-413f-b3ad-5eb8d18da3c0
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 4c3ce218-a9c8-4878-adc9-f1560c34fbfd
        userCondition: null
handle: language
name: Language
sortOrder: 3
