fieldLayouts:
  95c3bb1e-fea0-46c4-a555-e1a46aee9db3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: Meta
            type: craft\fieldlayoutelements\Heading
            uid: c80aa96e-739c-482f-b87b-c1d79b26e677
            userCondition: null
          -
            elementCondition: null
            fieldUid: a94b73a7-3163-422d-ad01-84f79ad1f533 # Image
            instructions: null
            label: 'Favicon - Dark'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b46d145-1174-4a93-990f-62a8cc13b859
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ad10c291-ef6d-4d79-8f1e-849473202717
            instructions: null
            label: 'Favicon - Light'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54018343-dc0b-4ba5-98c8-ede02092cf38
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: Header
            type: craft\fieldlayoutelements\Heading
            uid: 5700d365-070a-40e4-8b3c-a2ba5bb4db46
            userCondition: null
          -
            elementCondition: null
            fieldUid: 7f1344df-ba22-4ef0-8d35-de56c2afdc46
            instructions: 'The image in the middle of the header. Needs to me a .svg as it changes color with the text'
            label: 'Header - Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b41bdd5-9068-43e6-9d19-62d599f6ae2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39f07c34-8c1b-4b8b-93cd-bb77f023f47a # Richtext - Header
            instructions: 'Some text content that''s placed in the header. Preferably with some contact info'
            label: 'Header - Richtext'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fe4704c-fc45-4dd5-8895-db89f684d129
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c72c45c-e18d-4c63-85cb-502d284df753
            instructions: 'Shows up right below the richtext. Can contain some award badges for example. Images should be squares.'
            label: 'Header - Image links'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6cb40056-c062-4a26-ad28-0305ea29b9d3
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: ec9a4973-aa20-4080-8541-6afbf58a38aa
        userCondition: null
handle: settings
name: Settings
sortOrder: 1
