defaultPlacement: end
enableVersioning: true
handle: errorPage
name: 'Error page'
propagationMethod: all
siteSettings:
  1047e869-8b80-481b-bc87-ce5d9212ed20: # En
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
