defaultPlacement: end
enableVersioning: true
handle: index
name: Index
previewTargets:
  -
    __assoc__:
      -
        - label
        - Preview
      -
        - urlFormat
        - '@previewBaseUrl'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  78edf4a1-21b0-45a9-8a95-b3167b02af19: # springsummer
    enabledByDefault: true
    hasUrls: true
    template: index/_entry
    uriFormat: __home__
type: single
