defaultPlacement: end
enableVersioning: true
handle: mainMenu
name: 'Main menu'
propagationMethod: all
siteSettings:
  1047e869-8b80-481b-bc87-ce5d9212ed20: # En
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 1b720856-b7a3-477d-86a9-40f69409de98
type: structure
